package ORM;
// Generated 06-mar-2020 22:38:51 by Hibernate Tools 4.3.1



/**
 * Camion generated by hbm2java
 */
public class Camion  implements java.io.Serializable {


     private Integer idCamion;
     private String nombreCamion;
     private Integer velocidadMaxima;
     private Integer mma;
     private Double litrosTanque;

    public Camion() {
    }

    public Camion(String nombreCamion, Integer velocidadMaxima, Integer mma, Double litrosTanque) {
       this.nombreCamion = nombreCamion;
       this.velocidadMaxima = velocidadMaxima;
       this.mma = mma;
       this.litrosTanque = litrosTanque;
    }
   
    public Integer getIdCamion() {
        return this.idCamion;
    }
    
    public void setIdCamion(Integer idCamion) {
        this.idCamion = idCamion;
    }
    public String getNombreCamion() {
        return this.nombreCamion;
    }
    
    public void setNombreCamion(String nombreCamion) {
        this.nombreCamion = nombreCamion;
    }
    public Integer getVelocidadMaxima() {
        return this.velocidadMaxima;
    }
    
    public void setVelocidadMaxima(Integer velocidadMaxima) {
        this.velocidadMaxima = velocidadMaxima;
    }
    public Integer getMma() {
        return this.mma;
    }
    
    public void setMma(Integer mma) {
        this.mma = mma;
    }
    public Double getLitrosTanque() {
        return this.litrosTanque;
    }
    
    public void setLitrosTanque(Double litrosTanque) {
        this.litrosTanque = litrosTanque;
    }




}


