package acceso;
// Generated 17-ene-2020 21:44:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Camion generated by hbm2java
 */
public class Camion  implements java.io.Serializable {


     private Integer idCamion;
     private String nombreCamion;
     private Integer velocidadMaxima;
     private Integer mma;
     private Double litrosTanque;
     private Set camioneros = new HashSet(0);

    public Camion() {
    }

    public Camion(String nombreCamion, Integer velocidadMaxima, Integer mma, Double litrosTanque, Set camioneros) {
       this.nombreCamion = nombreCamion;
       this.velocidadMaxima = velocidadMaxima;
       this.mma = mma;
       this.litrosTanque = litrosTanque;
       this.camioneros = camioneros;
    }
   
    public Integer getIdCamion() {
        return this.idCamion;
    }
    
    public void setIdCamion(Integer idCamion) {
        this.idCamion = idCamion;
    }
    public String getNombreCamion() {
        return this.nombreCamion;
    }
    
    public void setNombreCamion(String nombreCamion) {
        this.nombreCamion = nombreCamion;
    }
    public Integer getVelocidadMaxima() {
        return this.velocidadMaxima;
    }
    
    public void setVelocidadMaxima(Integer velocidadMaxima) {
        this.velocidadMaxima = velocidadMaxima;
    }
    public Integer getMma() {
        return this.mma;
    }
    
    public void setMma(Integer mma) {
        this.mma = mma;
    }
    public Double getLitrosTanque() {
        return this.litrosTanque;
    }
    
    public void setLitrosTanque(Double litrosTanque) {
        this.litrosTanque = litrosTanque;
    }
    public Set getCamioneros() {
        return this.camioneros;
    }
    
    public void setCamioneros(Set camioneros) {
        this.camioneros = camioneros;
    }




}


