package acceso;
// Generated 17-ene-2020 21:44:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Camionero generated by hbm2java
 */
public class Camionero  implements java.io.Serializable {


     private Integer idCamionero;
     private Camion camion;
     private String nombre;
     private String apellidos;
     private Integer edad;
     private Double salario;
     private Set rutas = new HashSet(0);

    public Camionero() {
    }

    public Camionero(Camion camion, String nombre, String apellidos, Integer edad, Double salario, Set rutas) {
       this.camion = camion;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.edad = edad;
       this.salario = salario;
       this.rutas = rutas;
    }
   
    public Integer getIdCamionero() {
        return this.idCamionero;
    }
    
    public void setIdCamionero(Integer idCamionero) {
        this.idCamionero = idCamionero;
    }
    public Camion getCamion() {
        return this.camion;
    }
    
    public void setCamion(Camion camion) {
        this.camion = camion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public Set getRutas() {
        return this.rutas;
    }
    
    public void setRutas(Set rutas) {
        this.rutas = rutas;
    }




}


