package acceso;
// Generated 17-ene-2020 21:44:16 by Hibernate Tools 4.3.1



/**
 * Paquete generated by hbm2java
 */
public class Paquete  implements java.io.Serializable {


     private Integer idPaquete;
     private Ruta ruta;
     private Double peso;
     private Double altura;
     private Double ancho;
     private Double profundidad;

    public Paquete() {
    }

    public Paquete(Ruta ruta, Double peso, Double altura, Double ancho, Double profundidad) {
       this.ruta = ruta;
       this.peso = peso;
       this.altura = altura;
       this.ancho = ancho;
       this.profundidad = profundidad;
    }
   
    public Integer getIdPaquete() {
        return this.idPaquete;
    }
    
    public void setIdPaquete(Integer idPaquete) {
        this.idPaquete = idPaquete;
    }
    public Ruta getRuta() {
        return this.ruta;
    }
    
    public void setRuta(Ruta ruta) {
        this.ruta = ruta;
    }
    public Double getPeso() {
        return this.peso;
    }
    
    public void setPeso(Double peso) {
        this.peso = peso;
    }
    public Double getAltura() {
        return this.altura;
    }
    
    public void setAltura(Double altura) {
        this.altura = altura;
    }
    public Double getAncho() {
        return this.ancho;
    }
    
    public void setAncho(Double ancho) {
        this.ancho = ancho;
    }
    public Double getProfundidad() {
        return this.profundidad;
    }
    
    public void setProfundidad(Double profundidad) {
        this.profundidad = profundidad;
    }




}


